export default function Head() {
  return (
    <>
      <title>Anime Shoutouts</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="An website generated by create next app fo for anime fans" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
